### ISSUE TITLE
SSM 部分的课程链接

### ISSUE THREAD

**Issue by Reanon** [Seazean/JavaNotes#1]
感觉你SSM部分的笔记非常精美，想跟着一起学习，不仅想问这门SSM的课程是哪一家的，有相关的课程链接吗？

感谢大佬分享笔记~

**Comment by Seazean** [comment]
SSM看的黑马程序员的，其实我的Java和DB部分的笔记做的才是最好的，可以clone一下用typora打开，很精美，并且知识覆盖相对比较广

**Comment by Seazean** [comment]
> 感觉你SSM部分的笔记非常精美，想跟着一起学习，不仅想问这门SSM的课程是哪一家的，有相关的课程链接吗？
> 
> 感谢大佬分享笔记~

SSM看的黑马程序员的，其实我的Java和DB部分的笔记做的才是最好的，可以clone一下用typora打开，很精美，并且知识覆盖相对比较广

**Comment by Reanon** [comment]
您Java和DB部分的笔记我也看了，确实十分精美。同时看了B站上黑马的SSM课程，好像跟你笔记的不太一样，请问有具体的课程链接吗？

**Comment by Seazean** [comment]
> 您Java和DB部分的笔记我也看了，确实十分精美。同时看了B站上黑马的SSM课程，好像跟你笔记的不太一样，请问有具体的课程链接吗？

感谢老铁，记得点个star支持一下。SSM那里我看的黑马的，基础，至于很多源码部分是参考的尚硅谷，框架部分的知识看谁的都一样，只要会用就行。最重要的是要自己阅读源码，提升深度。

你看看这个视频是不，以前我也是在淘宝买的视频，哈哈哈。
链接：https://pan.baidu.com/s/17EeyKRLhUsqi5fIaM8bdnw 
提取码：6fnu

**Comment by Seazean** [comment]
下个月还会更新Spring、Mybatis 和 JUC并发包源码的笔记，非常欢迎老哥一起讨论

**Comment by Reanon** [comment]
感谢老哥，期待你的新笔记，到时候会持续关注~~

**Comment by wyg-lucas** [comment]
老哥太强了！

**Comment by Seazean** [comment]
> 老哥太强了！

哈哈  就是整理了一下自己的学习笔记，感谢认可
