### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by Yhooooo** [Seazean/JavaNotes#2]
非常感谢up主做的如此精美的笔记！
我在浏览笔记的时候有个别图片无法显示，应该是因为图片大于1M，gitee不显示的原因。
如在DB笔记中的：https://gitee.com/seazean/images/raw/master/DB/SQL分类.png    这一张图片就无法显示。希望能解决这个问题，比如可以在上传的时候压缩下图片？
还有一些图片不显示，似乎是up主给删除了？比如：java笔记中的 https://gitee.com/seazean/images/raw/master/Java/平衡二叉树左左.png       
最后感谢up的分享，已star，期待up主更新~

**Comment by Seazean** [comment]
非常感谢提出问题，数据结构那部分的笔记这次更新了一点，二叉树那部分图片删除因为个人觉得写的不好，附上了一个参考的文章
