### ISSUE TITLE
JUC --> AQS 关于CLH队列的描述有一个笔误

### ISSUE THREAD

**Issue by huangxin8899** [Seazean/JavaNotes#9]
内容为：“CLH是一种基于单向链表的高性能、公平的自旋锁”，这一块内容描述并不准确
经查阅资料发现，AQS中阻塞队列采用的是用双向链表保存，用prve和next相互链接。而AQS中条件队列是使用单向列表保存的，用nextWaiter来连接。阻塞队列和条件队列并不是使用的相同的数据结构。

**Comment by Seazean** [comment]
下一节有讲述这个问题，同步队列是双向链表，便于出队入队；条件队列是单向链表。其实我自己也没懂 CLH 队列的相关知识。

**Comment by huangxin8899** [comment]
你可以了解一下AQS里的内部类Node对象，里面每个成员的作用和内置方法，再来理解CLH就比较轻松了
